name: very_good_slide_puzzle
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.1

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  intl: ^0.17.0
  just_audio: ^0.9.18
  rive: ^0.8.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/rive/
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.otf
          weight: 400
    - family: NeuropolNova
      fonts:
        - asset: assets/fonts/NeuropolNova-Regular.ttf
          weight: 400
    - family: Charmonman
      fonts:
        - asset: assets/fonts/Charmonman-Regular.ttf
          weight: 400